// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Popsy;

#nullable disable

namespace Popsy.DataAccess.Migrations
{
    [DbContext(typeof(PopsyDbContext))]
    partial class PopsyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Popsy.Entities.TblDetalleOrdenDeCompraEntity", b =>
                {
                    b.Property<Guid>("id_recepcion_productos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cantidad_solicitada")
                        .HasColumnType("int");

                    b.Property<Guid>("id_orden_compra")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_producto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("unidad_presentacion_solicitada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_recepcion_productos");

                    b.ToTable("detalle_oden_compra");
                });

            modelBuilder.Entity("Popsy.Entities.TblDeterminarComprasTrasladosEntity", b =>
                {
                    b.Property<Guid>("determinar_compra_traslado_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("producto_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("punto_Venta_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("requiere_pedido_compra")
                        .HasColumnType("int");

                    b.HasKey("determinar_compra_traslado_id");

                    b.ToTable("determinar_compras_traslados");
                });

            modelBuilder.Entity("Popsy.Entities.TblInventarioDetalleEntity", b =>
                {
                    b.Property<Guid>("inventario_detalle_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("bodega_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("inventario_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("minima_unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("producto_punto_venta_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("inventario_detalle_id");

                    b.ToTable("inventariodetalle", "SIPOP");
                });

            modelBuilder.Entity("Popsy.Entities.TblInventariosEntity", b =>
                {
                    b.Property<Guid>("inventario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("codigo_inventario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_toma_fisica")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("punto_venta_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("tipo_inventario_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("usuario_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("inventario_id");

                    b.ToTable("inventarios", "SIPOP");
                });

            modelBuilder.Entity("Popsy.Entities.TblOrdenDeCompraEntity", b =>
                {
                    b.Property<Guid>("id_orden_compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("fecha_orden_compra")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("id_proveedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_punto_venta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("orden_compra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_orden_compra");

                    b.ToTable("orden_compra");
                });

            modelBuilder.Entity("Popsy.Entities.TblProductosEntity", b =>
                {
                    b.Property<Guid>("producto_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria_Producto1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria_Producto2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("producto_id");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("Popsy.Entities.TblProductosPedidosEntity", b =>
                {
                    b.Property<Guid>("producto_pedido_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("justificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("null_line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("pedido_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("producto_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("stock_actual")
                        .HasColumnType("int");

                    b.Property<int>("stock_transito")
                        .HasColumnType("int");

                    b.HasKey("producto_pedido_id");

                    b.ToTable("productos_pedidos");
                });

            modelBuilder.Entity("Popsy.Entities.TblProductosPuntosVentaEntity", b =>
                {
                    b.Property<Guid>("producto_punto_venta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cantidad_producto_maxima")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("producto_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("punto_distribucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("punto_venta_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("stock_actual")
                        .HasColumnType("int");

                    b.Property<int>("stock_transito")
                        .HasColumnType("int");

                    b.HasKey("producto_punto_venta_id");

                    b.ToTable("productos_puntos_venta");
                });

            modelBuilder.Entity("Popsy.Entities.TblProveedorRecepcionEntity", b =>
                {
                    b.Property<Guid>("id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("codigo_sap_producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigo_sap_proveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id_producto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_punto_de_venta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_proveedor");

                    b.ToTable("proveedor_recepcion");
                });

            modelBuilder.Entity("Popsy.Entities.TblPuntosVentasEntity", b =>
                {
                    b.Property<Guid>("punto_venta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("punto_venta_id");

                    b.ToTable("puntos_ventas");
                });

            modelBuilder.Entity("Popsy.Entities.TblRecepcionDeCompraEntity", b =>
                {
                    b.Property<Guid>("id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha_de_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_de_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unidad_presentacion_recibida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cantidad_recibida")
                        .HasColumnType("int");

                    b.Property<Guid>("id_detalle_orden_compra")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("numero_factura")
                        .HasColumnType("int");

                    b.HasKey("id_proveedor");

                    b.ToTable("recepcion_compra");
                });

            modelBuilder.Entity("Popsy.Entities.TblTipoInventarioEntity", b =>
                {
                    b.Property<Guid>("tipo_inventario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("abreviatura_inventario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_tipo_inventario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tipo_inventario_id");

                    b.ToTable("tipoinventario", "SIPOP");
                });

            modelBuilder.Entity("Popsy.Entities.TblUsuariosPuntosVentasEntity", b =>
                {
                    b.Property<Guid>("usuario_punto_venta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_eliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("punto_venta_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("usuario_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("usuario_punto_venta_id");

                    b.ToTable("usuarios_puntos_ventas");
                });

            modelBuilder.Entity("Popsy.Entities.VistaCategoriasProductosEntity", b =>
                {
                    b.Property<string>("categoria_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("categoria_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoria_id");

                    b.ToTable("vistacategoriasproductos", "SIPOP");
                });

            modelBuilder.Entity("Popsy.Entities.VistaMonitorInventarioEntity", b =>
                {
                    b.Property<Guid>("inventario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("codigo_inventario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_toma_fisica")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_tipo_inventario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("punto_venta_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("tipo_inventario_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("usuario_inventario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("inventario_id");

                    b.ToTable("vistamonitorInventario", "SIPOP");
                });

            modelBuilder.Entity("Popsy.Entities.VistaPedidosPuntoVentaEntity", b =>
                {
                    b.Property<Guid>("pedido_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("almacen_cs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("centro_cs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigo_punto_venta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_cs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("organizacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("punto_venta_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("pedido_id");

                    b.ToTable("vistapedidospuntoventa", "SIPOP");
                });

            modelBuilder.Entity("Popsy.Entities.VistaProductoFactoresConversionEntity", b =>
                {
                    b.Property<Guid>("producto_factor_conversion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("contador")
                        .HasColumnType("int");

                    b.Property<Guid>("factor_conversion_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("producto_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("unidad_base")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unidad_medida_alter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("producto_factor_conversion_id");

                    b.ToTable("vistaproductofactoresconversion", "SIPOP");
                });

            modelBuilder.Entity("Popsy.Entities.VistaProductosConStockEntity", b =>
                {
                    b.Property<Guid>("producto_punto_venta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cantidad_producto_maxima")
                        .HasColumnType("int");

                    b.Property<string>("categoria_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoria_producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("factor_conversion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("minima_unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_punto_venta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("presentacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("producto_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("punto_venta_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("stock_actual")
                        .HasColumnType("int");

                    b.HasKey("producto_punto_venta_id");

                    b.ToTable("vistaproductosconstock", "SIPOP");
                });

            modelBuilder.Entity("Popsy.Entities.VistaProductosParaInventarioEntity", b =>
                {
                    b.Property<Guid>("producto_punto_venta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cantidad_producto_maxima")
                        .HasColumnType("int");

                    b.Property<string>("categoria_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoria_producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("contador")
                        .HasColumnType("int");

                    b.Property<string>("factor_conversion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("minima_unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_punto_venta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("presentacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("producto_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("punto_venta_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("stock_actual")
                        .HasColumnType("int");

                    b.Property<string>("unidad_base")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unidad_medida_alter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("producto_punto_venta_id");

                    b.ToTable("vistaproductosparainventario", "SIPOP");
                });

            modelBuilder.Entity("Popsy.Entities.VistaPuntosVentaBodegasEntity", b =>
                {
                    b.Property<Guid>("bodegas_punto_venta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("bodega_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("codigo_punto_venta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_bodega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_punto_venta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("punto_venta_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("bodegas_punto_venta_id");

                    b.ToTable("vistapuntosventabodegas", "SIPOP");
                });

            modelBuilder.Entity("Popsy.Entities.VistaResumenInventarioEntity", b =>
                {
                    b.Property<Guid>("inventario_detalle_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("inventario_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nombre_producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_punto_venta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("producto_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("punto_venta_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("usuario_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("inventario_detalle_id");

                    b.ToTable("vistaresumeninventario", "SIPOP");
                });
#pragma warning restore 612, 618
        }
    }
}
