name: Desarrollo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Indica la plataforma adecuada para Windows Server

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Generar publish
        run: dotnet publish -c Release -o ./publish  # Ajusta el directorio de salida según tus necesidades

      - name: Modificar appsettings
        run: |
          $appSettingsPath = "./publish/appsettings.json"
          $appSettings = Get-Content $appSettingsPath | ConvertFrom-Json

          $environment = "Develop"  # Nombre de tu environment
          echo "Ambiente: $environment`n"

          $prefix = "${environment}_"

          # Recorrer las variables de entorno y reemplazar las claves correspondientes en el appsettings.json
          foreach ($envVar in (Get-ChildItem env:${prefix}* -ErrorAction SilentlyContinue)) {
            $key = $envVar.Name.Substring($prefix.Length)
            $value = $envVar.Value
            echo "Test: $key - $value`n"

            # Ignorar mayúsculas y minúsculas al comparar las claves del appsettings con las variables de entorno
            if ($appSettings.PSObject.Properties.Name -contains $key -or $appSettings.PSObject.Properties.Name -contains $key.ToLower() -or $appSettings.PSObject.Properties.Name -contains $key.ToUpper()) {
              echo "Variable de entorno encontrada: $key = $value"
              $appSettings.$key = $value
            }
          }

          $appSettings | ConvertTo-Json -Depth 10 | Set-Content $appSettingsPath

      - name: Comprimir archivos
        run: Compress-Archive -Path ./publish -DestinationPath ./publish.zip  # Cambia el nombre del archivo comprimido si lo deseas

      - name: Mostrar archivos generados
        run: ls -R ./publish ./publish.zip  # Puedes ajustar esta línea según lo que necesites mostrar

      - name: Guardar archivo comprimido como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: publish-artifact
          path: ./publish.zip
